/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var l=Object.defineProperty;var v=Object.getOwnPropertyDescriptor;var f=Object.getOwnPropertyNames;var w=Object.prototype.hasOwnProperty;var g=(a,e)=>{for(var t in e)l(a,t,{get:e[t],enumerable:!0})},p=(a,e,t,s)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of f(e))!w.call(a,o)&&o!==t&&l(a,o,{get:()=>e[o],enumerable:!(s=v(e,o))||s.enumerable});return a};var D=a=>p(l({},"__esModule",{value:!0}),a);var R={};g(R,{default:()=>i});module.exports=D(R);var d=require("obsidian"),E=/\[+|\]+/g,k=/\[\[\d{4}-\d{2}-\d{2}\]\]/g,O=/\[\[Overdue\]\]/i,b=/- \[ \]/,i=class extends d.Plugin{async markOverdue(){console.debug("Searching for overdue items");let e=new Date;e.setHours(0,0,0,0);for(let t of this.app.vault.getMarkdownFiles()){let o=new Date(`${t.basename}T00:00`)<e,r=!1,c=[],u=await this.app.vault.cachedRead(t);for(let n of u.split(`
`)){if(n.match(b)&&!n.match(O))if(o)n=`${n} [[Overdue]]`,r=!0;else for(let h of n.match(k)||[]){let m=h.replace(E,"");if(new Date(`${m}T00:00`)<e){n=`${n} [[Overdue]]`,r=!0;break}}c.push(n)}r&&(console.debug(`Marking overdue item(s) in ${t.path}`),await this.app.vault.modify(t,c.join(`
`)))}console.debug("Finished marking overdue items")}async onload(){this.addCommand({id:"overdue-mark",name:"Mark overdue items",callback:async()=>{await this.markOverdue()}}),this.interval=window.setInterval(()=>{new Date().getHours()==0&&this.markOverdue().catch(console.error)},1200*1e3),this.registerInterval(this.interval)}onunload(){window.clearInterval(this.interval)}};

/* nosourcemap */